In [1]:
# %%bash
# remove everything except this notebook
shopt -s extglob
rm -rf !("notebook.ipynb")
# to test any error in the terminal, use:
# !ipython3 -c "%run notebook.ipynb"

In [5]:
!conda list | grep fpocket

fpocket                   4.0.2                hbb826e7_0    conda-forge

In [2]:
!mkdir fpocket_output

In [18]:
!cp ../ref_Jupyter_Dock/test/Blind_Docking/1XOZ_clean_H.pdb .

In [19]:
!fpocket -f {'1XOZ_clean_H.pdb'} -d > {'pocket_descriptors.csv'}

In [21]:
import pandas as pd
pockets_data=pd.read_csv('pocket_descriptors.csv',sep=' ',index_col=[0])
pockets_data

,drug_score,volume,nb_asph,inter_chain,apol_asph_proportion,mean_asph_radius,as_density,mean_asph_solv_acc,mean_loc_hyd_dens,flex,...,val,trp,tyr,chain_1_type,chain_2_type,num_res_chain_1,num_res_chain_2,lig_het_tag,name_chain_1,name_chain_2
cav_id,,,,,,,,,,,,,,,,,,,,,
1,0.8741,1028.3990,139,0,0.6331,4.0200,6.8663,0.4647,60.2955,0.0,...,0,1,2,0,0,324,324,NaN,A,A
2,0.0452,560.6885,72,0,0.3333,3.7437,5.5622,0.4716,19.5833,0.0,...,0,1,0,0,0,324,324,NaN,A,A
3,0.0003,504.7823,37,0,0.3243,4.0605,5.1642,0.5894,10.6667,0.0,...,0,0,1,0,0,324,324,NaN,A,A
4,0.0021,383.0336,30,0,0.4667,3.9872,4.2452,0.6120,11.7143,0.0,...,0,0,0,0,0,324,324,NaN,A,A
5,0.0009,109.1321,23,0,0.3913,3.5100,2.0155,0.3504,8.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
6,0.0046,224.2952,34,0,0.4706,3.8398,3.2787,0.4623,15.0000,0.0,...,0,1,0,0,0,324,324,NaN,A,A
7,0.0005,220.8120,16,0,0.6250,3.9237,2.4631,0.6783,9.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
8,0.0004,220.2096,15,0,0.2667,3.9367,2.9664,0.5179,3.0000,0.0,...,0,1,0,0,0,324,324,NaN,A,A
9,0.0012,270.4959,33,0,0.6061,4.1402,2.1593,0.6400,19.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
10,0.0030,649.8133,52,0,0.2500,3.8994,5.4225,0.5173,10.1538,0.0,...,1,0,0,0,0,324,324,NaN,A,A
11,0.0017,193.2079,26,0,0.6538,3.7947,2.5979,0.6718,16.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
12,0.0014,1127.0513,107,0,0.3645,3.9622,8.3226,0.5096,21.0769,0.0,...,1,1,0,0,0,324,324,NaN,A,A
13,0.0009,365.0946,33,0,0.5758,3.8339,3.4003,0.4685,18.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
14,0.0002,285.5625,15,0,0.2000,3.7763,2.9304,0.4319,2.0000,0.0,...,0,0,1,0,0,324,324,NaN,A,A
15,0.0003,418.8799,34,0,0.3529,3.9346,3.8391,0.5044,10.3333,0.0,...,0,0,1,0,0,324,324,NaN,A,A
16,0.0001,292.5426,16,0,0.1875,3.8434,2.9985,0.5507,2.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
17,0.0012,202.4160,20,0,0.7500,3.8541,1.6062,0.4941,14.0000,0.0,...,1,0,0,0,0,324,324,NaN,A,A
18,0.0008,345.1190,16,0,0.4375,3.8732,3.4750,0.4447,6.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
19,0.0001,279.4922,16,0,0.3750,3.9213,2.6588,0.6055,5.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
20,0.0000,237.7742,17,0,0.0588,3.9535,2.8521,0.5774,0.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
21,0.0002,304.5737,22,0,0.1364,3.8877,2.4383,0.4918,2.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A
22,0.0004,407.7753,24,0,0.2917,4.1979,3.5434,0.5977,6.0000,0.0,...,0,0,0,0,0,324,324,NaN,A,A